version: '3.8'
services:
  # frontend:
  #   build: ./frontend/
  #   container_name: frontend
  #   ports: 
  #     - "3000:3000"
  backend: 
    build: ./server/
    container_name: backend
    restart: always
    tty: true
    env_file:
      - ./server/.env
    environment:
      - IS_BUILD=true
    command: php -S 0.0.0.0:8000 /server/router.php
    ports: 
      - "8000:8000"